# Generated by Django 2.2.2 on 2019-07-03 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('attach', models.FileField(upload_to='document/uploads/%Y/%m/', verbose_name='添付ファイル')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_user', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_user', models.CharField(max_length=200)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
